//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace FacialLandmarks
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// A single detected face with bounding box and metadata
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A single detected face with bounding box and metadata")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class DetectedFace
    {
    
        private double _normalizedX;
    
        private double _normalizedY;
    
        private double _normalizedWidth;
    
        private double _normalizedHeight;
    
        private int _x;
    
        private int _y;
    
        private int _width;
    
        private int _height;
    
        private double _confidence;
    
        private int _faceId;
    
        public DetectedFace()
        {
        }
    
        protected DetectedFace(DetectedFace other)
        {
            _normalizedX = other._normalizedX;
            _normalizedY = other._normalizedY;
            _normalizedWidth = other._normalizedWidth;
            _normalizedHeight = other._normalizedHeight;
            _x = other._x;
            _y = other._y;
            _width = other._width;
            _height = other._height;
            _confidence = other._confidence;
            _faceId = other._faceId;
        }
    
        /// <summary>
        /// Relative X coordinate of top-left corner of bounding box
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("normalized_x")]
        [System.ComponentModel.DescriptionAttribute("Relative X coordinate of top-left corner of bounding box")]
        public double NormalizedX
        {
            get
            {
                return _normalizedX;
            }
            set
            {
                _normalizedX = value;
            }
        }
    
        /// <summary>
        /// Relative Y coordinate of top-left corner of bounding box
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("normalized_y")]
        [System.ComponentModel.DescriptionAttribute("Relative Y coordinate of top-left corner of bounding box")]
        public double NormalizedY
        {
            get
            {
                return _normalizedY;
            }
            set
            {
                _normalizedY = value;
            }
        }
    
        /// <summary>
        /// Relative width of bounding box
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("normalized_width")]
        [System.ComponentModel.DescriptionAttribute("Relative width of bounding box")]
        public double NormalizedWidth
        {
            get
            {
                return _normalizedWidth;
            }
            set
            {
                _normalizedWidth = value;
            }
        }
    
        /// <summary>
        /// Relative height of bounding box
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("normalized_height")]
        [System.ComponentModel.DescriptionAttribute("Relative height of bounding box")]
        public double NormalizedHeight
        {
            get
            {
                return _normalizedHeight;
            }
            set
            {
                _normalizedHeight = value;
            }
        }
    
        /// <summary>
        /// X coordinate of top-left corner of bounding box
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("x", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("X coordinate of top-left corner of bounding box")]
        public int X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }
    
        /// <summary>
        /// Y coordinate of top-left corner of bounding box
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("y", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Y coordinate of top-left corner of bounding box")]
        public int Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
    
        /// <summary>
        /// Width of the bounding box in pixels
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("width", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Width of the bounding box in pixels")]
        public int Width
        {
            get
            {
                return _width;
            }
            set
            {
                _width = value;
            }
        }
    
        /// <summary>
        /// Height of the bounding box in pixels
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("height", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Height of the bounding box in pixels")]
        public int Height
        {
            get
            {
                return _height;
            }
            set
            {
                _height = value;
            }
        }
    
        /// <summary>
        /// Detection confidence score between 0.0 and 1.0
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("confidence", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Detection confidence score between 0.0 and 1.0")]
        public double Confidence
        {
            get
            {
                return _confidence;
            }
            set
            {
                _confidence = value;
            }
        }
    
        /// <summary>
        /// Unique identifier for this face within the result set
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("face_id", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Unique identifier for this face within the result set")]
        public int FaceId
        {
            get
            {
                return _faceId;
            }
            set
            {
                _faceId = value;
            }
        }
    
        public System.IObservable<DetectedFace> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new DetectedFace(this)));
        }
    
        public System.IObservable<DetectedFace> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new DetectedFace(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("normalized_x = " + _normalizedX + ", ");
            stringBuilder.Append("normalized_y = " + _normalizedY + ", ");
            stringBuilder.Append("normalized_width = " + _normalizedWidth + ", ");
            stringBuilder.Append("normalized_height = " + _normalizedHeight + ", ");
            stringBuilder.Append("x = " + _x + ", ");
            stringBuilder.Append("y = " + _y + ", ");
            stringBuilder.Append("width = " + _width + ", ");
            stringBuilder.Append("height = " + _height + ", ");
            stringBuilder.Append("confidence = " + _confidence + ", ");
            stringBuilder.Append("face_id = " + _faceId);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Facial landmarks for a single detected face
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Facial landmarks for a single detected face")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class FacialLandmarks
    {
    
        private int _faceId;
    
        private System.Collections.Generic.List<LandmarkPoint> _landmarks;
    
        private double _confidence;
    
        private System.Collections.Generic.List<int> _landmarkSubsetIndices;
    
        public FacialLandmarks()
        {
            _landmarks = new System.Collections.Generic.List<LandmarkPoint>();
            _landmarkSubsetIndices = new System.Collections.Generic.List<int>();
        }
    
        protected FacialLandmarks(FacialLandmarks other)
        {
            _faceId = other._faceId;
            _landmarks = other._landmarks;
            _confidence = other._confidence;
            _landmarkSubsetIndices = other._landmarkSubsetIndices;
        }
    
        /// <summary>
        /// Corresponds to the face_id in DetectedFace
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("face_id", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Corresponds to the face_id in DetectedFace")]
        public int FaceId
        {
            get
            {
                return _faceId;
            }
            set
            {
                _faceId = value;
            }
        }
    
        /// <summary>
        /// Array of 468 facial landmark points as [x, y, z] coordinates
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("landmarks", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Array of 468 facial landmark points as [x, y, z] coordinates")]
        public System.Collections.Generic.List<LandmarkPoint> Landmarks
        {
            get
            {
                return _landmarks;
            }
            set
            {
                _landmarks = value;
            }
        }
    
        /// <summary>
        /// Landmark detection confidence score
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("confidence", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Landmark detection confidence score")]
        public double Confidence
        {
            get
            {
                return _confidence;
            }
            set
            {
                _confidence = value;
            }
        }
    
        /// <summary>
        /// Indices of landmark points for quick access to facial features
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("landmark_subset_indices", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Indices of landmark points for quick access to facial features")]
        public System.Collections.Generic.List<int> LandmarkSubsetIndices
        {
            get
            {
                return _landmarkSubsetIndices;
            }
            set
            {
                _landmarkSubsetIndices = value;
            }
        }
    
        public System.IObservable<FacialLandmarks> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new FacialLandmarks(this)));
        }
    
        public System.IObservable<FacialLandmarks> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new FacialLandmarks(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("face_id = " + _faceId + ", ");
            stringBuilder.Append("landmarks = " + _landmarks + ", ");
            stringBuilder.Append("confidence = " + _confidence + ", ");
            stringBuilder.Append("landmark_subset_indices = " + _landmarkSubsetIndices);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// A single 3D landmark point
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("A single 3D landmark point")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class LandmarkPoint
    {
    
        private double _normalizedX;
    
        private double _normalizedY;
    
        private double _normalizedZ;
    
        private int _x;
    
        private int _y;
    
        private int _z;
    
        public LandmarkPoint()
        {
        }
    
        protected LandmarkPoint(LandmarkPoint other)
        {
            _normalizedX = other._normalizedX;
            _normalizedY = other._normalizedY;
            _normalizedZ = other._normalizedZ;
            _x = other._x;
            _y = other._y;
            _z = other._z;
        }
    
        /// <summary>
        /// X coordinate (normalized 0.0-1.0 relative to image width)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("normalized_x")]
        [System.ComponentModel.DescriptionAttribute("X coordinate (normalized 0.0-1.0 relative to image width)")]
        public double NormalizedX
        {
            get
            {
                return _normalizedX;
            }
            set
            {
                _normalizedX = value;
            }
        }
    
        /// <summary>
        /// Y coordinate (normalized 0.0-1.0 relative to image height)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("normalized_y")]
        [System.ComponentModel.DescriptionAttribute("Y coordinate (normalized 0.0-1.0 relative to image height)")]
        public double NormalizedY
        {
            get
            {
                return _normalizedY;
            }
            set
            {
                _normalizedY = value;
            }
        }
    
        /// <summary>
        /// Z coordinate (depth relative to image plane)
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("normalized_z")]
        [System.ComponentModel.DescriptionAttribute("Z coordinate (depth relative to image plane)")]
        public double NormalizedZ
        {
            get
            {
                return _normalizedZ;
            }
            set
            {
                _normalizedZ = value;
            }
        }
    
        /// <summary>
        /// X coordinate in pixels
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("x", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("X coordinate in pixels")]
        public int X
        {
            get
            {
                return _x;
            }
            set
            {
                _x = value;
            }
        }
    
        /// <summary>
        /// Y coordinate in pixels
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("y", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Y coordinate in pixels")]
        public int Y
        {
            get
            {
                return _y;
            }
            set
            {
                _y = value;
            }
        }
    
        /// <summary>
        /// Z coordinate in pixels
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("z", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Z coordinate in pixels")]
        public int Z
        {
            get
            {
                return _z;
            }
            set
            {
                _z = value;
            }
        }
    
        public System.IObservable<LandmarkPoint> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new LandmarkPoint(this)));
        }
    
        public System.IObservable<LandmarkPoint> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new LandmarkPoint(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("normalized_x = " + _normalizedX + ", ");
            stringBuilder.Append("normalized_y = " + _normalizedY + ", ");
            stringBuilder.Append("normalized_z = " + _normalizedZ + ", ");
            stringBuilder.Append("x = " + _x + ", ");
            stringBuilder.Append("y = " + _y + ", ");
            stringBuilder.Append("z = " + _z);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Focused output schema for C# interop - represents the complete result from Python face detection and facial landmarks functions
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Focused output schema for C# interop - represents the complete result from Python" +
        " face detection and facial landmarks functions")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class FacialAnalysisOutput
    {
    
        private System.Collections.Generic.List<DetectedFace> _faces;
    
        private System.Collections.Generic.List<FacialLandmarks> _landmarks;
    
        private double _processingTimeMs;
    
        private int _imageWidth;
    
        private int _imageHeight;
    
        private int _faceCount;
    
        public FacialAnalysisOutput()
        {
            _faces = new System.Collections.Generic.List<DetectedFace>();
            _landmarks = new System.Collections.Generic.List<FacialLandmarks>();
        }
    
        protected FacialAnalysisOutput(FacialAnalysisOutput other)
        {
            _faces = other._faces;
            _landmarks = other._landmarks;
            _processingTimeMs = other._processingTimeMs;
            _imageWidth = other._imageWidth;
            _imageHeight = other._imageHeight;
            _faceCount = other._faceCount;
        }
    
        /// <summary>
        /// Array of detected faces with bounding boxes and confidence scores
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("faces", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Array of detected faces with bounding boxes and confidence scores")]
        public System.Collections.Generic.List<DetectedFace> Faces
        {
            get
            {
                return _faces;
            }
            set
            {
                _faces = value;
            }
        }
    
        /// <summary>
        /// Array of facial landmarks for each detected face
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("landmarks", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Array of facial landmarks for each detected face")]
        public System.Collections.Generic.List<FacialLandmarks> Landmarks
        {
            get
            {
                return _landmarks;
            }
            set
            {
                _landmarks = value;
            }
        }
    
        /// <summary>
        /// Processing time in milliseconds
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("processing_time_ms", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Processing time in milliseconds")]
        public double ProcessingTimeMs
        {
            get
            {
                return _processingTimeMs;
            }
            set
            {
                _processingTimeMs = value;
            }
        }
    
        /// <summary>
        /// Width of the processed image in pixels
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("image_width", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Width of the processed image in pixels")]
        public int ImageWidth
        {
            get
            {
                return _imageWidth;
            }
            set
            {
                _imageWidth = value;
            }
        }
    
        /// <summary>
        /// Height of the processed image in pixels
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("image_height", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Height of the processed image in pixels")]
        public int ImageHeight
        {
            get
            {
                return _imageHeight;
            }
            set
            {
                _imageHeight = value;
            }
        }
    
        /// <summary>
        /// Total number of faces detected
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("face_count", Required=Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DescriptionAttribute("Total number of faces detected")]
        public int FaceCount
        {
            get
            {
                return _faceCount;
            }
            set
            {
                _faceCount = value;
            }
        }
    
        public System.IObservable<FacialAnalysisOutput> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new FacialAnalysisOutput(this)));
        }
    
        public System.IObservable<FacialAnalysisOutput> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new FacialAnalysisOutput(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("faces = " + _faces + ", ");
            stringBuilder.Append("landmarks = " + _landmarks + ", ");
            stringBuilder.Append("processing_time_ms = " + _processingTimeMs + ", ");
            stringBuilder.Append("image_width = " + _imageWidth + ", ");
            stringBuilder.Append("image_height = " + _imageHeight + ", ");
            stringBuilder.Append("face_count = " + _faceCount);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into JSON strings.")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    public partial class SerializeToJson
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.SerializeObject(value));
        }

        public System.IObservable<string> Process(System.IObservable<DetectedFace> source)
        {
            return Process<DetectedFace>(source);
        }

        public System.IObservable<string> Process(System.IObservable<FacialLandmarks> source)
        {
            return Process<FacialLandmarks>(source);
        }

        public System.IObservable<string> Process(System.IObservable<LandmarkPoint> source)
        {
            return Process<LandmarkPoint>(source);
        }

        public System.IObservable<string> Process(System.IObservable<FacialAnalysisOutput> source)
        {
            return Process<FacialAnalysisOutput>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of JSON strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<DetectedFace>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<FacialLandmarks>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<LandmarkPoint>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<FacialAnalysisOutput>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromJson()
        {
            Type = new Bonsai.Expressions.TypeMapping<FacialAnalysisOutput>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromJson),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value));
        }
    }
}