//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace FacialLandmarks
{
#pragma warning disable // Disable all warnings

    /// <summary>
    /// Predefined landmark subsets for different use cases
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum LandmarkSubset
    {

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "face_oval")]
        FaceOval = 0,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "left_eye")]
        LeftEye = 1,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "right_eye")]
        RightEye = 2,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "left_eyebrow")]
        LeftEyebrow = 3,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "right_eyebrow")]
        RightEyebrow = 4,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "nose")]
        Nose = 5,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "lips")]
        Lips = 6,

        [System.Runtime.Serialization.EnumMemberAttribute(Value = "all")]
        All = 7,
    }


    /// <summary>
    /// Configuration for facial processing pipeline
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.5.0.0 (Newtonsoft.Json v13.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Configuration for facial processing pipeline")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class ProcessingConfig
    {

        private double _faceDetectionConfidence;

        private int _faceModelSelection;

        private int _maxNumFaces;

        private bool _refineLandmarks;

        private double _landmarkDetectionConfidence;

        private double _landmarkTrackingConfidence;

        private bool _enableFaceDetection;

        private bool _enableLandmarkDetection;

        private bool _enableParallelProcessing;

        private bool _drawFaceBoxes;

        private bool _drawFaceKeypoints;

        private bool _drawLandmarks;

        private LandmarkSubset _landmarkSubset;

        private bool _drawLandmarkConnections;

        private bool _drawDetailedLandmarks;

        private bool _showLandmarkIndices;

        private double? _minDetectionConfidence;

        private double? _minTrackingConfidence;

        private string _outputPath;

        private bool _saveVideo;

        private bool _showFps;

        public ProcessingConfig()
        {
            _faceDetectionConfidence = 0.5D;
            _faceModelSelection = 0;
            _maxNumFaces = 1;
            _refineLandmarks = true;
            _landmarkDetectionConfidence = 0.5D;
            _landmarkTrackingConfidence = 0.5D;
            _enableFaceDetection = true;
            _enableLandmarkDetection = true;
            _enableParallelProcessing = false;
            _drawFaceBoxes = false;
            _drawFaceKeypoints = true;
            _drawLandmarks = true;
            _landmarkSubset = LandmarkSubset.All;
            _drawLandmarkConnections = true;
            _drawDetailedLandmarks = true;
            _showLandmarkIndices = false;
            _saveVideo = false;
            _showFps = true;
        }

        protected ProcessingConfig(ProcessingConfig other)
        {
            _faceDetectionConfidence = other._faceDetectionConfidence;
            _faceModelSelection = other._faceModelSelection;
            _maxNumFaces = other._maxNumFaces;
            _refineLandmarks = other._refineLandmarks;
            _landmarkDetectionConfidence = other._landmarkDetectionConfidence;
            _landmarkTrackingConfidence = other._landmarkTrackingConfidence;
            _enableFaceDetection = other._enableFaceDetection;
            _enableLandmarkDetection = other._enableLandmarkDetection;
            _enableParallelProcessing = other._enableParallelProcessing;
            _drawFaceBoxes = other._drawFaceBoxes;
            _drawFaceKeypoints = other._drawFaceKeypoints;
            _drawLandmarks = other._drawLandmarks;
            _landmarkSubset = other._landmarkSubset;
            _drawLandmarkConnections = other._drawLandmarkConnections;
            _drawDetailedLandmarks = other._drawDetailedLandmarks;
            _showLandmarkIndices = other._showLandmarkIndices;
            _minDetectionConfidence = other._minDetectionConfidence;
            _minTrackingConfidence = other._minTrackingConfidence;
            _outputPath = other._outputPath;
            _saveVideo = other._saveVideo;
            _showFps = other._showFps;
        }

        /// <summary>
        /// Minimum confidence threshold for face detection
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("face_detection_confidence")]
        [System.ComponentModel.DescriptionAttribute("Minimum confidence threshold for face detection")]
        public double FaceDetectionConfidence
        {
            get
            {
                return _faceDetectionConfidence;
            }
            set
            {
                _faceDetectionConfidence = value;
            }
        }

        /// <summary>
        /// 0 for short-range, 1 for full-range model
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("face_model_selection")]
        [System.ComponentModel.DescriptionAttribute("0 for short-range, 1 for full-range model")]
        public int FaceModelSelection
        {
            get
            {
                return _faceModelSelection;
            }
            set
            {
                _faceModelSelection = value;
            }
        }

        /// <summary>
        /// Maximum number of faces to detect
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("max_num_faces")]
        [System.ComponentModel.DescriptionAttribute("Maximum number of faces to detect")]
        public int MaxNumFaces
        {
            get
            {
                return _maxNumFaces;
            }
            set
            {
                _maxNumFaces = value;
            }
        }

        /// <summary>
        /// Whether to refine landmarks around eyes and lips
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("refine_landmarks")]
        [System.ComponentModel.DescriptionAttribute("Whether to refine landmarks around eyes and lips")]
        public bool RefineLandmarks
        {
            get
            {
                return _refineLandmarks;
            }
            set
            {
                _refineLandmarks = value;
            }
        }

        /// <summary>
        /// Minimum confidence threshold for landmark detection
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("landmark_detection_confidence")]
        [System.ComponentModel.DescriptionAttribute("Minimum confidence threshold for landmark detection")]
        public double LandmarkDetectionConfidence
        {
            get
            {
                return _landmarkDetectionConfidence;
            }
            set
            {
                _landmarkDetectionConfidence = value;
            }
        }

        /// <summary>
        /// Minimum confidence threshold for landmark tracking
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("landmark_tracking_confidence")]
        [System.ComponentModel.DescriptionAttribute("Minimum confidence threshold for landmark tracking")]
        public double LandmarkTrackingConfidence
        {
            get
            {
                return _landmarkTrackingConfidence;
            }
            set
            {
                _landmarkTrackingConfidence = value;
            }
        }

        /// <summary>
        /// Whether to enable face detection
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("enable_face_detection")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable face detection")]
        public bool EnableFaceDetection
        {
            get
            {
                return _enableFaceDetection;
            }
            set
            {
                _enableFaceDetection = value;
            }
        }

        /// <summary>
        /// Whether to enable landmark detection
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("enable_landmark_detection")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable landmark detection")]
        public bool EnableLandmarkDetection
        {
            get
            {
                return _enableLandmarkDetection;
            }
            set
            {
                _enableLandmarkDetection = value;
            }
        }

        /// <summary>
        /// Whether to enable parallel processing
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("enable_parallel_processing")]
        [System.ComponentModel.DescriptionAttribute("Whether to enable parallel processing")]
        public bool EnableParallelProcessing
        {
            get
            {
                return _enableParallelProcessing;
            }
            set
            {
                _enableParallelProcessing = value;
            }
        }

        /// <summary>
        /// Whether to draw face bounding boxes
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("draw_face_boxes")]
        [System.ComponentModel.DescriptionAttribute("Whether to draw face bounding boxes")]
        public bool DrawFaceBoxes
        {
            get
            {
                return _drawFaceBoxes;
            }
            set
            {
                _drawFaceBoxes = value;
            }
        }

        /// <summary>
        /// Whether to draw face keypoints
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("draw_face_keypoints")]
        [System.ComponentModel.DescriptionAttribute("Whether to draw face keypoints")]
        public bool DrawFaceKeypoints
        {
            get
            {
                return _drawFaceKeypoints;
            }
            set
            {
                _drawFaceKeypoints = value;
            }
        }

        /// <summary>
        /// Whether to draw facial landmarks
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("draw_landmarks")]
        [System.ComponentModel.DescriptionAttribute("Whether to draw facial landmarks")]
        public bool DrawLandmarks
        {
            get
            {
                return _drawLandmarks;
            }
            set
            {
                _drawLandmarks = value;
            }
        }

        /// <summary>
        /// Subset of landmarks to draw
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("landmark_subset")]
        [System.ComponentModel.DescriptionAttribute("Subset of landmarks to draw")]
        public LandmarkSubset LandmarkSubset
        {
            get
            {
                return _landmarkSubset;
            }
            set
            {
                _landmarkSubset = value;
            }
        }

        /// <summary>
        /// Whether to draw connections between landmarks
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("draw_landmark_connections")]
        [System.ComponentModel.DescriptionAttribute("Whether to draw connections between landmarks")]
        public bool DrawLandmarkConnections
        {
            get
            {
                return _drawLandmarkConnections;
            }
            set
            {
                _drawLandmarkConnections = value;
            }
        }

        /// <summary>
        /// Whether to draw detailed landmarks
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("draw_detailed_landmarks")]
        [System.ComponentModel.DescriptionAttribute("Whether to draw detailed landmarks")]
        public bool DrawDetailedLandmarks
        {
            get
            {
                return _drawDetailedLandmarks;
            }
            set
            {
                _drawDetailedLandmarks = value;
            }
        }

        /// <summary>
        /// Whether to show landmark indices
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("show_landmark_indices")]
        [System.ComponentModel.DescriptionAttribute("Whether to show landmark indices")]
        public bool ShowLandmarkIndices
        {
            get
            {
                return _showLandmarkIndices;
            }
            set
            {
                _showLandmarkIndices = value;
            }
        }

        /// <summary>
        /// Backward compatibility alias for face_detection_confidence
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("min_detection_confidence")]
        [System.ComponentModel.DescriptionAttribute("Backward compatibility alias for face_detection_confidence")]
        public double? MinDetectionConfidence
        {
            get
            {
                return _minDetectionConfidence;
            }
            set
            {
                _minDetectionConfidence = value;
            }
        }

        /// <summary>
        /// Backward compatibility alias for landmark_tracking_confidence
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Newtonsoft.Json.JsonPropertyAttribute("min_tracking_confidence")]
        [System.ComponentModel.DescriptionAttribute("Backward compatibility alias for landmark_tracking_confidence")]
        public double? MinTrackingConfidence
        {
            get
            {
                return _minTrackingConfidence;
            }
            set
            {
                _minTrackingConfidence = value;
            }
        }

        /// <summary>
        /// Output path for saving results
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("output_path")]
        [System.ComponentModel.DescriptionAttribute("Output path for saving results")]
        public string OutputPath
        {
            get
            {
                return _outputPath;
            }
            set
            {
                _outputPath = value;
            }
        }

        /// <summary>
        /// Whether to save processed video
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("save_video")]
        [System.ComponentModel.DescriptionAttribute("Whether to save processed video")]
        public bool SaveVideo
        {
            get
            {
                return _saveVideo;
            }
            set
            {
                _saveVideo = value;
            }
        }

        /// <summary>
        /// Whether to show FPS information
        /// </summary>
        [Newtonsoft.Json.JsonPropertyAttribute("show_fps")]
        [System.ComponentModel.DescriptionAttribute("Whether to show FPS information")]
        public bool ShowFps
        {
            get
            {
                return _showFps;
            }
            set
            {
                _showFps = value;
            }
        }

        public System.IObservable<ProcessingConfig> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new ProcessingConfig(this)));
        }

        public System.IObservable<ProcessingConfig> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new ProcessingConfig(this));
        }

        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("face_detection_confidence = " + _faceDetectionConfidence + ", ");
            stringBuilder.Append("face_model_selection = " + _faceModelSelection + ", ");
            stringBuilder.Append("max_num_faces = " + _maxNumFaces + ", ");
            stringBuilder.Append("refine_landmarks = " + _refineLandmarks + ", ");
            stringBuilder.Append("landmark_detection_confidence = " + _landmarkDetectionConfidence + ", ");
            stringBuilder.Append("landmark_tracking_confidence = " + _landmarkTrackingConfidence + ", ");
            stringBuilder.Append("enable_face_detection = " + _enableFaceDetection + ", ");
            stringBuilder.Append("enable_landmark_detection = " + _enableLandmarkDetection + ", ");
            stringBuilder.Append("enable_parallel_processing = " + _enableParallelProcessing + ", ");
            stringBuilder.Append("draw_face_boxes = " + _drawFaceBoxes + ", ");
            stringBuilder.Append("draw_face_keypoints = " + _drawFaceKeypoints + ", ");
            stringBuilder.Append("draw_landmarks = " + _drawLandmarks + ", ");
            stringBuilder.Append("landmark_subset = " + _landmarkSubset + ", ");
            stringBuilder.Append("draw_landmark_connections = " + _drawLandmarkConnections + ", ");
            stringBuilder.Append("draw_detailed_landmarks = " + _drawDetailedLandmarks + ", ");
            stringBuilder.Append("show_landmark_indices = " + _showLandmarkIndices + ", ");
            stringBuilder.Append("min_detection_confidence = " + _minDetectionConfidence + ", ");
            stringBuilder.Append("min_tracking_confidence = " + _minTrackingConfidence + ", ");
            stringBuilder.Append("output_path = " + _outputPath + ", ");
            stringBuilder.Append("save_video = " + _saveVideo + ", ");
            stringBuilder.Append("show_fps = " + _showFps);
            return true;
        }

        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into JSON strings.
    /// </summary>
    public partial class SerializeToJson
    {
        public System.IObservable<string> Process(System.IObservable<ProcessingConfig> source)
        {
            return Process<ProcessingConfig>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of JSON strings into data model objects.
    /// </summary>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<ProcessingConfig>))]
    public partial class DeserializeFromJson : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    }
}